apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rjg7wpruz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rjg7wpruz-python 
  name: rjg7wpruz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rjg7wpruz-python 
