apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rjg7wpruz-python-gitops
  description: This is GitOps manifest for rjg7wpruz-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rjg7wpruz-python
    backstage.io/kubernetes-id: rjg7wpruz-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rjg7wpruz-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rjg7wpruz-python
